- name: Install docker and docker compose on ubuntu 20+
  hosts: all

  tasks:
    - name: Install apt pre-requirements
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        update_cache: true
      become: true

    - name: Add Docker gpg key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add Docker apt repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
        state: present
      become: true

    - name: Install Docker Engine and Compose plugin
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true
      become: true

    - name: Add user to the Docker group(to allow run docker without sudo)
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        group: docker
      become: true

    - name: Check docker & compose
      ansible.builtin.shell: |
        docker version
        docker compose version
        docker run hello-world
      register: _docker_check_cmd
      changed_when: _docker_check_cmd.rc != 0
      ignore_errors: true
      become: true

    - name: Print docker check result
      ansible.builtin.debug:
        msg:
          - "STDOUT:"
          - "{{ _docker_check_cmd.stdout_lines }}"
          - "STDERR:"
          - "{{ _docker_check_cmd.stderr_lines }}"
